name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 (Linting)
        run: |
          pip install flake8 flake8-html
          mkdir -p reports/flake8
          flake8 --format=html --htmldir=reports/flake8 || true

      - name: Run Pytest
        run: |
          pip install pytest pytest-html
          mkdir -p reports/pytest
          pytest --html=reports/pytest/report.html --self-contained-html

      - name: Upload Linting Report
        uses: actions/upload-artifact@v4
        with:
          name: flake8-report
          path: reports/flake8

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/pytest